import { randomUUID } from 'node:crypto';

export interface CreatePrResult {
  prUrl: string;
  prNumber: number;
  branch: string;
}

function getGitHubConfig() {
  const token = process.env.GITHUB_TOKEN;
  const owner = process.env.GITHUB_OWNER;
  const repo = process.env.GITHUB_REPO;
  const baseBranch = process.env.GITHUB_BASE_BRANCH || 'main';
  if (!token || !owner || !repo) {
    throw new Error('GitHub integration is not configured. Set GITHUB_TOKEN, GITHUB_OWNER and GITHUB_REPO.');
  }
  return { token, owner, repo, baseBranch };
}

async function githubApi(path: string, options: RequestInit): Promise<unknown> {
  const { token, owner, repo } = getGitHubConfig();
  const url = `https://api.github.com/repos/${owner}/${repo}${path}`;
  const res = await fetch(url, {
    ...options,
    headers: {
      Accept: 'application/vnd.github+json',
      Authorization: `Bearer ${token}`,
      'X-GitHub-Api-Version': '2022-11-28',
      'Content-Type': 'application/json',
      ...(options.headers || {}),
    },
  });
  const body = (await res.json().catch(() => ({}))) as Record<string, unknown>;
  if (!res.ok) {
    throw new Error(`GitHub API ${options.method || 'GET'} ${path} failed (${res.status}): ${body.message || JSON.stringify(body)}`);
  }
  return body;
}

function encodeContent(content: string): string {
  return Buffer.from(content, 'utf8').toString('base64');
}

export async function createOptimizedTerraformPR(
  original: string,
  optimized: string,
  summary: string,
  proposalId: string,
): Promise<CreatePrResult> {
  const { baseBranch } = getGitHubConfig();
  const branch = `terrapilot/${proposalId.toLowerCase()}-${randomUUID().slice(0, 8)}`;

  // 1. Get base branch SHA.
  const baseRef = (await githubApi(`/git/refs/heads/${baseBranch}`, { method: 'GET' })) as {
    object: { sha: string };
  };

  // 2. Create branch.
  await githubApi('/git/refs', {
    method: 'POST',
    body: JSON.stringify({
      ref: `refs/heads/${branch}`,
      sha: baseRef.object.sha,
    }),
  });

  // 3. Create or update file. We use a fixed path for the optimized manifest.
  const path = 'terraform/main.tf';
  let existingSha: string | undefined;
  try {
    const fileMeta = (await githubApi(`/contents/${path}?ref=${baseBranch}`, { method: 'GET' })) as { sha: string };
    existingSha = fileMeta.sha;
  } catch {
    existingSha = undefined;
  }

  await githubApi(`/contents/${path}`, {
    method: 'PUT',
    body: JSON.stringify({
      message: `TerraPilot: optimize Terraform (${proposalId})\n\n${summary}`,
      content: encodeContent(optimized),
      branch,
      ...(existingSha ? { sha: existingSha } : {}),
    }),
  });

  // 4. Open pull request.
  const pr = (await githubApi('/pulls', {
    method: 'POST',
    body: JSON.stringify({
      title: `TerraPilot optimization: ${proposalId}`,
      head: branch,
      base: baseBranch,
      body: `## TerraPilot proposed change\n\n${summary}\n\n**Proposal ID:** ${proposalId}\n**Optimized file:** \`${path}\`\n\nThis PR was generated by the TerraPilot HITL pipeline after human approval. No cloud resources were modified directly.`,
    }),
  })) as { html_url: string; number: number };

  return { prUrl: pr.html_url, prNumber: pr.number, branch };
}

export function isGitHubConfigured(): boolean {
  return Boolean(process.env.GITHUB_TOKEN && process.env.GITHUB_OWNER && process.env.GITHUB_REPO);
}
